general:
  review_col: "review"
  metadata_col: "meta"
  rating_column: "rating"
  response_column: "resp"
  review_column: "text"

data_downloader:
  base_url: "https://datarepo.eng.ucsd.edu/mcauley_group/gdrive/googlelocal/"
  output_folder: "${hydra:runtime.cwd}/data/gzip"
  use_subset: true
  use_metadata: false

data_extractor:
  input_folder: "${data_downloader.output_folder}"
  output_folder: "${hydra:runtime.cwd}/data/extracted"
  key_columns: ["rating", "text", "resp"]
  suffix: "extracted.json"
  batch_size: 5
  remove_gzip_files: false

data_processor:
  input_folder: "${data_extractor.output_folder}/${general.review_col}"
  output_folder: "${hydra:runtime.cwd}/data/processed"
  suffix: "processed.csv" # "processed.parquet"
  batch_to_process: 3
  remove_json_files: false
  regex_pattern:
    # Remove special characters except for punctuations
    '[^A-Za-z0-9\s.,!?]': ''

    # Remove any http or https links
    '(?:https?)\S+': ''

    # Remove any potential contact numbers
    '\b\d{9,}\b': ''

    # Replace two or more consecutive spaces with a single space
    '\s+': ' '

data_splitter:
  input_filepath: "${data_processor.output_folder}/${data_processor.suffix}"
  output_folder: "${hydra:runtime.cwd}/data/split"
  suffix: ["train.csv", "val.csv", "test.csv"]
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  seed: 42
  split_tolerance: 0.01

dataloader:
  input_folder: "${data_splitter.output_folder}"
  batch_size: 32
  max_length: 64
  encoder_model: "roberta-large"
  decoder_model: "microsoft/DialoGPT-medium"
  encoder_decoder_model: "t5-base"

modelling:
  general:
    checkpoint_path: "${hydra:runtime.cwd}/models"
    device: "mps"
    epochs: 10
    patience: 3
    gradient_clipping_threshold: 0.1
    random_seed: 42

  model:
    encoder: "${dataloader.encoder_model}"
    decoder: "${dataloader.decoder_model}"
    encoder_decoder: "${dataloader.encoder_decoder_model}"
    sentiment_classes: 3

  loss_weights:
    sentiment_loss_weightage: 1.0
    response_loss_weightage: 1.0

  optimizer:
    learning_rate: 1e-4

  scheduler:
    factor: 0.1
    patience: 5
